name: Bump the step version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "a version"
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for now...
      - id: version
        run: echo "result=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
      - id: current-version
        run: echo "result=$(.ci/get-version)" >> $GITHUB_OUTPUT
      - id: branch
        name: create a branch
        run: |
          readonly branch_name='bump/${{ steps.version.outputs.result }}'

          git switch -c "$branch_name"
          echo "result=$branch_name" >> $GITHUB_OUTPUT
      - run: .ci/reflect-version '${{ steps.version.outputs.result }}'
      - name: commit and create a pull request
        run: |
          git config user.email 'services+github-actions@deploygate.com'
          git config user.name 'deploygate-github-actions'

          git add .
          git commit -m ":tada: bump up to ${{ steps.version.outputs.result }}"
          git push origin '${{ steps.branch.outputs.result }}'
      - name: create a pull request
        run: |
          readonly pr_body="$(mktemp)"

          .ci/evaluate-pr-body-template ${{ steps.current-version.outputs.result }} ${{ steps.branch.outputs.result }} | tee "$pr_body"

          gh pr create \
            --base master \
            --title "Bump up to ${{ steps.version.outputs.result }}" \
            --body-file "$pr_body" \
            --reviewer '${{ github.actor }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
